Meghan_FinancialPortal/Models/Budget.cs
namespace Meghan_FinancialPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Budget
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budget()
        {
            BudgetItems = new HashSet<BudgetItem>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        public int HouseholdId { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BudgetItem> BudgetItems { get; set; }

        public virtual Household Household { get; set; }
    }
}

Meghan_FinancialPortal/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Meghan_FinancialPortal.Models;

namespace Meghan_FinancialPortal.Controllers
{
    public class BudgetsController : Controller
    {
        private FinancialPortal fdb = new FinancialPortal();

        // GET: Budgets
        public ActionResult Index()
        {
            var budgets = fdb.Budgets.Include(b => b.Household);
            return View(budgets.ToList());
        }

        // GET: Budgets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = fdb.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            return View(budget);
        }

        // GET: Budgets/Create
        public ActionResult Create()
        {
            ViewBag.HouseholdId = new SelectList(fdb.Households, "Id", "Name");
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,HouseholdId")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                fdb.Budgets.Add(budget);
                fdb.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.HouseholdId = new SelectList(fdb.Households, "Id", "Name", budget.HouseholdId);
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Budget budget = fdb.Budgets.Find(id);
            if (budget == null)
            {
                return HttpNotFound();
            }
            ViewBag.HouseholdId = new SelectList(fdb.Households, "Id", "Name", budget.HouseholdId);
            return View(budget);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,HouseholdId")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                fdb.Entry(budget).State = EntityState.Modified;
                fdb.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.HouseholdId = new SelectList(fdb.Households, "Id", "Name", budget.HouseholdId);
            return View(budget);
        }

        // GET: Budgets/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Budget budget = db.Budgets.Find(id);
        //    if (budget == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(budget);
        //}

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Budget budget = fdb.Budgets.Find(id);
            fdb.Budgets.Remove(budget);
            fdb.SaveChanges();
            ViewBag.PreviousUrl = System.Web.HttpContext.Current.Request.UrlReferrer.ToString();
            return Redirect(ViewBag.PreviousUrl);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                fdb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Meghan_FinancialPortal/Views/Budgets/Create.cshtml
@model Meghan_FinancialPortal.Models.Budget

<div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-android-checkbox-outline"></i>Budgets / </span>Create</h1>
</div>
<div class="panel">
    <div class="panel-heading">
        <div class="panel-title">New Budget</div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <fieldset class="form-group">
            <label for="form-group-input-1">Name</label>
            <input type="text" class="form-control" name="Name" placeholder="Name of budget...">
        </fieldset>
        <fieldset class="form-group">
            <label for="form-group-input-2">Household</label>
            @Html.DropDownList("HouseholdId", null, "--- None selected ---", htmlAttributes: new { @class = "form-control" })
        </fieldset>
        <fieldset class="form-group text-right">
            <button type="submit" class="btn btn-primary">Save</button>
        </fieldset>
    }
</div>

Meghan_FinancialPortal/Views/Budgets/Delete.cshtml
@model Meghan_FinancialPortal.Models.Budget

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Budget</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Household.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Household.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Meghan_FinancialPortal/Views/Budgets/Details.cshtml
@model Meghan_FinancialPortal.Models.Budget

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Budget</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Household.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Household.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Meghan_FinancialPortal/Views/Budgets/Edit.cshtml
@model Meghan_FinancialPortal.Models.Budget

<div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-android-checkbox-outline"></i>Budgets / </span>Edit</h1>
</div>
<div class="panel">
    <div class="panel-heading">
        <div class="panel-title">Edit Budget</div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.Id)
        <fieldset class="form-group">
            <label for="form-group-input-1">Name</label>
            <input type="text" class="form-control" name="Name" vale="@Model.Name" placeholder="Name of budget...">
        </fieldset>
        <fieldset class="form-group">
            <label for="form-group-input-2">Household</label>
            @Html.DropDownList("HouseholdId", null, "--- None selected ---", htmlAttributes: new { @class = "form-control" })
        </fieldset>
        <fieldset class="form-group text-right">
            <button type="submit" class="btn btn-primary">Save</button>
        </fieldset>
    }
</div>

Meghan_FinancialPortal/Views/Budgets/Index.cshtml
@model IEnumerable<Meghan_FinancialPortal.Models.Budget>

<div class="page-header">
    <h1 class="pull-xs-left"><span class="text-muted font-weight-light"><i class="page-header-icon ion-monitor"></i>Budgets / </span>Progress</h1>
</div>

<div class="col-md-8">
    @foreach (var budget in Model)
    {
        <div class="panel">
            <div class="panel-heading">
                <span class="panel-title">@budget.Name</span>
                <div class="panel-heading-controls" style="width: 30%; max-width: 140px;">
                    <div class="progress progress-striped active" style="width: 100%">
                        <div class="progress-bar progress-bar-danger" style="width: 60%;"></div>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                @budget.Household.Name
            </div>
            <div class="panel-footer">
                <a href="@Url.Action("Edit", "Budgets", new { id = budget.Id })" class="btn btn-primary btn-sm"><i class="fa fa-edit"></i></a>
                <a href="@Url.Action("Delete", "Budgets", new { id = budget.Id })" class="btn btn-primary btn-sm"><i class="fa fa-trash"></i></a>
            </div>
        </div>
    }
</div>