Meghan_FinancialPortal/Models/Helpers/HouseholdHelper.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;

namespace Meghan_FinancialPortal.Models.Helpers
{
    public class HouseholdHelper
    {
        private static Household household = new Household();
        private static ApplicationDbContext adb = new ApplicationDbContext();
        private static FinancialPortal fdb = new FinancialPortal();
        private static UserHelper userHelper = new UserHelper();

        public bool IsUnique(string houseName) //check to see if household name is unique when creating it
        {
            foreach (Household house in fdb.Households.ToList())
            {
                if (house.Name == houseName)
                {
                    return false;
                }
            }
            return true;
        }

        public void RemoveUserFromHousehold(string userId, int householdId) //remove user from Household
        {
            if (userHelper.InHousehold(userId, householdId))
            {
                Household household = fdb.Households.Find(householdId);
                var delUser = adb.Users.Find(userId);

                household.Users.Remove(delUser);
                fdb.Entry(household).State = EntityState.Modified; //modifies existing Household record
                fdb.SaveChanges();
            }
        }
    }
}

Meghan_FinancialPortal/Models/Household.cs
namespace Meghan_FinancialPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Household
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Household()
        {
            Users = new HashSet<ApplicationUser>();
            Budgets = new HashSet<Budget>();
            Invites = new HashSet<Invite>();
            PersonalAccounts = new HashSet<PersonalAccount>();
            Categories = new HashSet<Category>();
        }

        public int Id { get; set; }

        public string Name { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicationUser> Users { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Budget> Budgets { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invite> Invites { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalAccount> PersonalAccounts { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Category> Categories { get; set; }
    }
}

Meghan_FinancialPortal/Models/Invite.cs
namespace Meghan_FinancialPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Invite
    {
        public int Id { get; set; }

        public int HouseholdId { get; set; }

        public string Email { get; set; }

        public Guid HHToken { get; set; }

        public DateTimeOffset InviteDate { get; set; }

        [StringLength(128)]
        public string InvitedById { get; set; }

        public bool HasBeenUsed { get; set; }

        public virtual ApplicationUser User { get; set; }

        public virtual Household Household { get; set; }
    }
}

Meghan_FinancialPortal/Models/ViewModels/HouseholdViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Meghan_FinancialPortal.Models.ViewModels
{
    public class HouseholdViewModel
    {
        public bool IsJoinHouse { get; set; }
        public int? HouseholdId { get; set; }
        public string HouseholdName { get; set; }
        public ApplicationUser Member { get; set; }
    }
}

Meghan_FinancialPortal/Controllers/HouseholdsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Meghan_FinancialPortal.Models;
using Meghan_FinancialPortal.Models.Helpers;
using Meghan_FinancialPortal.Models.ViewModels;
using Microsoft.AspNet.Identity;

namespace Meghan_FinancialPortal.Controllers
{
    public class HouseholdsController : Controller
    {
        private FinancialPortal fdb = new FinancialPortal();
        private ApplicationDbContext adb = new ApplicationDbContext();
        private HouseholdHelper househldHelper = new HouseholdHelper();

        // GET: Households
        public ActionResult Index()
        {
            return View(fdb.Households.ToList());
        }

        // GET: Households/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = fdb.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // GET: Households/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Households/Create
        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Create(HouseholdViewModel vm)
        {
            //Create new household
            Household household = new Household();

            //check if name is unique
            if(househldHelper.IsUnique(household.Name) == true)
            {
                household.Name = vm.HouseholdName;
            }
            else
            {
                TempData["NameNotUnique"] = "The Household name you entered is not unique. Please enter a different name.";
                return RedirectToAction("Create"); //bring create household view back up...
            }
            
            // add household to database
            fdb.Households.Add(household);
            fdb.SaveChanges();

            //Add the current user as the first member of the new household
            var user = adb.Users.Find(User.Identity.GetUserId());
            household.Users.Add(user);
            fdb.SaveChanges();
            await ControllerContext.HttpContext.RefreshAuthentication(user); //refresh thier cookies and direct them to their dashboard

            return RedirectToAction("Index", "Home");
        }

        // GET: Households/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Household household = fdb.Households.Find(id);
            if (household == null)
            {
                return HttpNotFound();
            }
            return View(household);
        }

        // POST: Households/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name")] Household household)
        {
            if (ModelState.IsValid)
            {
                fdb.Entry(household).State = EntityState.Modified;
                fdb.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(household);
        }

        //GET : Invite
        public ActionResult Invite()
        {
            return View();
        }

        //POST: INVITE
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> Invite(string email)
        {
            var code = Guid.NewGuid();
            var callbackUrl = Url.Action("CreateJoinHousehold", "Home", new { code }, protocol: Request.Url.Scheme);

            //send email
            var from = "Financial Portal<meghankcombs@gmail.com>";
            var to = email;
            var sendEmail = new MailMessage(from, to)
            {
                Subject = "Financial Portal: Household Invite",
                Body = "You have been invited to a household! Click here to join: " + callbackUrl,
                IsBodyHtml = true
            };
            var svc = new PersonalEmail();
            await svc.SendAsync(sendEmail);

            //create invite record
            Invite model = new Invite();
            model.Email = email;
            model.HHToken = code;
            model.HouseholdId = User.Identity.GetHouseholdId().Value;
            model.InviteDate = DateTimeOffset.Now;
            model.InvitedById = User.Identity.GetUserId();

            fdb.Invites.Add(model);
            fdb.SaveChanges();

            return RedirectToAction("Index", "Home");
        }

        //POST: Leave Household
        [HttpPost]
        [Authorize]
        public async Task<ActionResult> LeaveHousehold(int householdId)
        {
            //already in household details view, so can get household id through route values and pass in here
            Household household = fdb.Households.Find(householdId); //find household by id passed in
            ApplicationUser user = adb.Users.Find(User.Identity.GetUserId()); //get user's id
            household.Users.Remove(user);
            fdb.SaveChanges();

            await ControllerContext.HttpContext.RefreshAuthentication(user); //method in extensions class
            return RedirectToAction("Index", "Home");
        }
        
        // POST: Households/Delete/5
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Household household = fdb.Households.Find(id);
            fdb.Households.Remove(household);
            fdb.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                fdb.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Meghan_FinancialPortal/Views/Households/Create.cshtml
@model Meghan_FinancialPortal.Models.Household

<div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-android-checkbox-outline"></i>Household / </span>Create</h1>
</div>
<div class="panel">
    <div class="panel-heading">
        <div class="panel-title">New Household</div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <fieldset class="form-group">
            <label for="form-group-input-1">Name</label>
            <input type="text" class="form-control" name="Name" placeholder="Enter household name...">
        </fieldset>
        <fieldset class="form-group text-right">
            <button type="submit" class="btn btn-primary">Create</button>
        </fieldset>
    }
</div>

@section scripts {
    @if (TempData.ContainsKey("NameNotUnique"))
    {
        <script>
                    $(function () {
                        swal('Oops!', '@TempData["NameNotUnique"]', 'warning');
                    });
        </script>
    }
}

Meghan_FinancialPortal/Views/Households/Delete.cshtml
@model Meghan_FinancialPortal.Models.Household

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Household</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

Meghan_FinancialPortal/Views/Households/Details.cshtml
@model Meghan_FinancialPortal.Models.Household

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Household</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Meghan_FinancialPortal/Views/Households/Edit.cshtml
@model Meghan_FinancialPortal.Models.Household

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Household</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Meghan_FinancialPortal/Views/Households/Index.cshtml
@model IEnumerable<Meghan_FinancialPortal.Models.Household>

<div class="page-header">
    <h1><span class="text-muted font-weight-light"><i class="page-header-icon ion-ios-keypad"></i>Household</span></h1>
</div>
<div class="panel">
    <div class="panel-heading">
        <a href="@Url.Action("Create", "Households")" class="panel-title"><i class="fa fa-calendar-plus-o"></i> Create Household</a>
    </div>
    <div class="panel-body">
        <div class="table-primary">
            <table class="table table-striped table-bordered" id="householdsTable">
                <thead>
                    <tr>
                        <th>Name</th>
                        <th>People in Household</th>
                        <th># of Acconts</th>
                        <th># of Invites Sent</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var household in Model)
                    {
                        <tr class="odd gradeX">
                            <td>@household.Name</td>
                            <td class="center"><span class="label label-info">@household.Users.Count()</span></td>
                            <td class="center"><span class="label label-warning">@household.PersonalAccounts.Count()</span></td>
                            <td class="center"><span class="label label-primary">@household.Invites.Count()</span></td>
                            <td class="center">
                                <div class="btn-group" style="margin-top: 4px;">
                                    <a href="@Url.Action("Details", "Households", new { id = household.Id })" class="btn btn-xs btn-primary btn-outline myIndexBtns" data-toggle="tooltip" title="Details"><i class="fa fa-list"></i></a>
                                    <a href="@Url.Action("Edit", "Households", new { id = household.Id })" class="btn btn-xs btn-primary btn-outline myIndexBtns" data-toggle="tooltip" title="Edit"><i class="fa fa-edit"></i></a>
                                    <a href="@Url.Action("Delete", "Households", new { id = household.Id })" class="btn btn-xs btn-primary btn-outline myIndexBtns" data-toggle="tooltip" title="Delete"><i class="fa fa-trash"></i></a>
                                </div>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $('#householdsTable').DataTable();
    </script>
}

Meghan_FinancialPortal/Views/Households/Invite.cshtml
<!-- need form for invite post method -->